//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FourSer.Analyzers
{
    using System;
    using System.Reflection;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FourSer.Analyzers.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Type names should be all uppercase..
        /// </summary>
        internal static string AnalyzerDescription
        {
            get
            {
                return ResourceManager.GetString("AnalyzerDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Type name &apos;{0}&apos; contains lowercase letters.
        /// </summary>
        internal static string AnalyzerMessageFormat
        {
            get
            {
                return ResourceManager.GetString("AnalyzerMessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Type name contains lowercase letters.
        /// </summary>
        internal static string AnalyzerTitle
        {
            get
            {
                return ResourceManager.GetString("AnalyzerTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to When using PolymorphicMode.SingleTypeId, the TypeIdType property must match the type of the PolymorphicOption's ID..
        /// </summary>
        internal static string SerializeCollectionSingleTypeId_Description {
            get {
                return ResourceManager.GetString("SerializeCollectionSingleTypeId_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The type of 'TypeIdType' ({0}) does not match the type of the 'PolymorphicOption' ID ({1}).
        /// </summary>
        internal static string SerializeCollectionSingleTypeId_MessageFormat {
            get {
                return ResourceManager.GetString("SerializeCollectionSingleTypeId_MessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Type of 'TypeIdType' and 'PolymorphicOption' do not match.
        /// </summary>
        internal static string SerializeCollectionSingleTypeId_Title {
            get {
                return ResourceManager.GetString("SerializeCollectionSingleTypeId_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mark only one PolymorphicOptionAttribute with isDefault = true for a polymorphic member..
        /// </summary>
        internal static string PolymorphicOptionMultipleDefaults_Description {
            get {
                return ResourceManager.GetString("PolymorphicOptionMultipleDefaults_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Only one 'PolymorphicOption' can be marked as the default.
        /// </summary>
        internal static string PolymorphicOptionMultipleDefaults_MessageFormat {
            get {
                return ResourceManager.GetString("PolymorphicOptionMultipleDefaults_MessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Multiple default polymorphic options.
        /// </summary>
        internal static string PolymorphicOptionMultipleDefaults_Title {
            get {
                return ResourceManager.GetString("PolymorphicOptionMultipleDefaults_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A property cannot be used as a reference for multiple different kinds of references (e.g. CountSizeReference and TypeIdProperty)..
        /// </summary>
        internal static string FSER009_Description {
            get {
                return ResourceManager.GetString("FSER009_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The property '{0}' is used as a reference for both '{1}' and '{2}'.
        /// </summary>
        internal static string FSER009_MessageFormat {
            get {
                return ResourceManager.GetString("FSER009_MessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Conflicting property reference.
        /// </summary>
        internal static string FSER009_Title {
            get {
                return ResourceManager.GetString("FSER009_Title", resourceCulture);
            }
        }
    }
}
